### ISSUE TITLE
Example of how to use with SimpleITK?

### ISSUE THREAD

**Issue by str4w** [InsightSoftwareConsortium/itkwidgets#107]
It is probably obvious, but I couldn't figure it out.  itkwidgets.view does not take a SimpleITK image directly.  Is there a way to visualize a SimpleITK image besides either passing via numpy, or reloading with regular ITK?

If not, I would make this a feature request.

**Comment by thewtex** [comment]
Yes, conversion of a `SimpleITK.Image` to a NumPy array is possible, but metadata will be lost. Saving to file and reading with `itk.imread` will preserve metadata.

SimpleITK should provide a conversion to `itk.Image`. Since the `itk` Python package provides more functionality, and [ITK 5's interface is more Pythonic](https://discourse.itk.org/t/itk-5-0-beta-1-pythonic-interface/1271), this is not a priority.

**Comment by thewtex** [comment]
`SimpleITK.Image` support was added in #228
