### ISSUE TITLE
name of this package and consistency

### ISSUE THREAD

**Issue by banesullivan** [InsightSoftwareConsortium/itkwidgets#169]
The full name of this package is quite a mouthful and the repo name varies from the Python package name which can be a point of confusion for new users. I'm curious if it would be of interest to rename the repository to match the Python package's name: `itkwidgets`

Also, this package appears to be growing (or at least on a path) towards being a visualization widget toolkit for a lot more than just images. The name `itkwidgets` might imply some sort of limitation to image datasets only. Would it be of interest to rename this package to something more general and in line with the package's roots in VTKjs? Perhaps something along the lines of `vtkwidgets` or `vtkjswidgets`?

This came to mind as I'm thinking about how I might implement interoperability between `itkwidgets` and `pyvista` (ref #154)

**Comment by thewtex** [comment]
@banesullivan good point. The repository / package name mismatch is an unnecessary point of confusion that also came up in conversations with @GenevieveBuckley . On the one hand, there are other repository / package name differences like scikit-image / skimage, scikit-learn / sklearn, etc. Also, it is nice to have *jupyter* explicitly in the name, because *Jupyter* is a popular topic and it is a focus of the project. But, the mental impedance mismatch when finding the project and installing may outweigh the benefits.

The scope certainly does extend beyond images. While ITK's strength is images, it also supports other data structures. And, we support pyvista, Dask, NumPy, ... The core implementation is based on ipywidgets, ITK, and vtk.js. While a name like `itkvtkjswidgets` is descriptively accurate, it is also too long to write for every import statement :man_shrugging: .

I will target a rename of the repository to `itkwidgets` for the 0.18.0 release.
