### ISSUE TITLE
Add automated testing for the examples

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/itkwidgets#54]
Possibly use `nbval`:

 https://github.com/computationalmodelling/nbval

**Comment by thewtex** [comment]
nbval does not appear to be helpful for WebGL rendering.

Investigate the [Robot Framework](http://robotframework.org/) h/t @tonyfast

**Comment by tonyfast** [comment]
@thewtex I don't know much about robot, but the homie @bollwyvl does.  I wanted to make sure he joined the party.

**Comment by bollwyvl** [comment]
Howdy! I've been using robot framework in a few places to test jupyterlab
stuff. I got interested after seeing:

https://github.com/datakurre/robotkernel

And have also been working on a more IPython-like kernel with some lab
bells and whistles (not open source... yet).

My heavy lifter in working with lab is seleniumlibrary:

http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html

Here are a few examples, all of which are run in ci:

https://github.com/deathbeds/jyve/blob/master/tests/acceptance/Kernels.robot

https://github.com/deathbeds/jupyterlab-fonts/blob/master/tests/acceptance/Editor.robot

https://github.com/bollwyvl/robotlab/blob/master/tests/acceptance/RobotLab/02_Robot_Notebook.robot

I am particularly happy with the ones in robotlab, as they are currently
running on win/Mac/Linux with azure pipelines. Not saying your should _try_
robotlab, as I'm still working on it...

Note that all those tests copy-pasta from each other in tests/resources/,
rather than being a reusable library. Gotta fix that!

I've been thinking robotframework-jupyter would include basic widget
support and, initially, lab and notebook classic, and eventually, nteract.
Definitely have some support for testing slide output. Probably also start
with a user model, to be ready for collaborative editing.

All the usual browser-based testing caveats apply: browser version
sensitivity, ci system flake, slow, thinking like a browser, thinking like
ANOTHER browser, etc.

I've been trying to make sure the stack works well with conda-forge
dependencies, so it's pretty easy (once you have browsers!) to get up and
running on all the platforms.

What I haven't tried yet is to get front-end coverage from robot tests. I
presume i'd have to do an instrumented build, then build lab again, then
figure out how to get out the instrumentation before each browser reset.
But that's not really the goal anyway, I guess.

An upcoming version of selenium library will include per-element
screenshots, but for now, I've been pulling the whole screen and using "get
webelements" to pull out it's bounding box.

Anyhow, happy to help in any way! In totally unrelated (sorta) stuff, we're
trying to do a "cadlab" and are evaluating the merits of itk-widgets for
certain kinds of visualisation: cfd, from, etc!

https://github.com/bollwyvl/cadlab

**Comment by thewtex** [comment]
Thanks for the tips and help, Tony and Nick!

> I am particularly happy with the ones in robotlab, as they are currently
running on win/Mac/Linux with azure pipelines.

That is incredible! Well done!

> Note that all those tests copy-pasta from each other in tests/resources/,
rather than being a reusable library. Gotta fix that!

I am seeing the potential! As I understand it, this could help test Jupyter notebook output with complex renderings, and your work has proven it could work across browsers and across platforms. For someone not versed in the Robot Framework like myself, and for a use case like testing the itkwidgets examples, we want to easily set up verifications that Jupyter cell output has the "right" content. We need some wrapping abstraction that will 1) run the notebooks and capture images of the cell output in some organized fashion, or DOM contents, 2) re-run and verify with fuzzy correspondance to the images or DOM with checks against multiple browsers.

> Anyhow, happy to help in any way! In totally unrelated (sorta) stuff, we're
trying to do a "cadlab" and are evaluating the merits of itk-widgets for
certain kinds of visualisation: cfd, from, etc!

Wow, very cool! itkwidgets could also help add volume image -> 3D model capabilities, which people love for bringing in real world geometry into their CAD models, 3D printing, ...

**Comment by thewtex** [comment]
We are using `treebeardtech/nbmake-action`
