### ISSUE TITLE
AttributeError: 'Viewer' object has no attribute 'add_point_set'

### ISSUE THREAD

**Issue by sunscale** [InsightSoftwareConsortium/itkwidgets#616]
When I run the example code **NumPyArrayPointSet.ipynb**, an error occurs:

> AttributeError                            Traceback (most recent call last)
> Cell In[10], line 1
> ----> 1 viewer.add_point_set(point_set_2)
> 
> AttributeError: 'Viewer' object has no attribute 'add_point_set'

Is there anything wrong with my installation? Thanks.

**Comment by bnmajor** [comment]
@sunscale That is likely because that feature is available on master but not yet in a release. I am guessing you are on `1.0a23` at the moment?

Until `1.0a24` is released you can use the master branch a few ways:

1. Clone and build locally
    1. git clone git@github.com:InsightSoftwareConsortium/itkwidgets.git
    2. cd /path/to/repo
    3. pip install -e ".[all]"
2. Use the url
    1. Replace the line `!{sys.executable} -m pip install -q "itkwidgets[all]>=1.0a23"` with `!{sys.executable} -m pip install -q git+https://github.com/InsightSoftwareConsortium/itkwidgets.git`

Additionally, the default does not yet have suppport for the point set controls. If you would like to use them (to toggle point color, size, shape) you pass `ui="reference"` to the call to `view` to get access to those controls for now.

**Comment by sunscale** [comment]
It works now! Thanks for your kind help.
